### ISSUE TITLE
Error loading the program

### ISSUE THREAD

**Issue by MarkMcCormick** [bring2lite/bring2lite#3]
Every time I try to run the program it crashes. I was looking through the code and there is a syntax error every time I try compiling the code. Seems to me that it's failing to install the module.

**Comment by Rasmus-Riis** [comment]
Same here. Gives me  the error:
 0%|                                                     | 0/1 [00:00<?, ?it/s]extract overflow
  0%|                                                     | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    main()
  File "main.py", line 15, in main
    my_gui.process()
  File "/home/riis/bring2lite/bring2lite/classes/gui.py", line 142, in process
    self.start_processing_sqlite()
  File "/home/riis/bring2lite/bring2lite/classes/gui.py", line 153, in start_processing_sqlite
    self.d = self.sqlp.parse(i, self.output, self.format)
  File "/home/riis/bring2lite/bring2lite/classes/sqlite_parser.py", line 36, in parse
    self._parse_body()
  File "/home/riis/bring2lite/bring2lite/classes/sqlite_parser.py", line 125, in _parse_body
    result = super(SQLiteParser, self)._parse_page(one_page)
  File "/home/riis/bring2lite/bring2lite/classes/parser.py", line 56, in _parse_page
    return self._extract_cells(page, num_of_cells_in_frame, schema_offset)
  File "/home/riis/bring2lite/bring2lite/classes/parser.py", line 96, in _extract_cells
    overflow_content = self._extract_overflow_pages(page, cell_offset + current_index + payload_length - header_length, var_P - var_K)
  File "/home/riis/bring2lite/bring2lite/classes/parser.py", line 137, in _extract_overflow_pages
    f.seek(self.page_size * (next_page))
OSError: [Errno 22] Invalid argument
